version: "3.8"

services:
  react18-app:
    container_name: react18-app
    build:
      context: .
    tty: true
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - 5173:5173